name: happy_bird_day
description: A simple calender app to track birthdays.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.5.0"

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.0.2

  sqflite: ^2.0.0+4

  provider:

  flutter_local_notifications: ^9.2.0

  flutter_native_timezone: ^2.0.0

  workmanager: ^0.5.0

  google_fonts: ^3.0.1

  cupertino_icons: ^1.0.3

  url_launcher: ^6.0.18

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
